<a href="https://colab.research.google.com/github/ad3919-hash/fds-unit-1/blob/main/RA2411056010283_Unit_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating an array with arange**

In [ ]:
import numpy as np
arr = np.arange(7)
print(arr)


[0 1 2 3 4 5 6]


**Reshaping an array and checking size**

In [ ]:
import numpy as np
arr = np.arange(8).reshape(2,4)
print(arr)
print()
arr.size


[[0 1 2 3]
 [4 5 6 7]]



8

**Creating an identity matrix with eye**

In [ ]:
import numpy as np
arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Eye matrix with offsets and identity**

In [ ]:
import numpy as np
print(np.eye(3,5,1))
print()
print(np.eye(8,4,0))
print()
print(np.eye(8,4,1))
print()
print(np.eye(8,4,-1))
print()
arr = np.identity(4)
print(arr)


[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Creating an empty array**

In [ ]:
import numpy as np
arr = np.empty(4)
print(arr)


[1. 1. 1. 1.]


**Zeros, Ones, and Full arrays**

In [ ]:
import numpy as np
arr = np.zeros((2,4))
print(arr)
print()
arrr = np.ones((3,6))
print(arrr)
ar = np.full((2,2),3)
print(ar)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[3 3]
 [3 3]]


**Creating an array of ones**

In [ ]:
import numpy as np
arr = np.ones((2,4))
print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Reshape and dimension**

In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print("Dimnesion", arr.ndim)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

Dimnesion 2


**Full array and shape**

In [ ]:
import numpy as np
arr = np.full((2,5),7)
print(arr)
print()
arr.shape


[[7 7 7 7 7]
 [7 7 7 7 7]]



(2, 5)

**Array slicing**

In [ ]:
import numpy as np
arr = np.array([2,34,41,32,23,122])
print(arr)
print()
print(arr[1:3])


[  2  34  41  32  23 122]

[34 41]


**More slicing examples**

In [ ]:
import numpy as np
arr = np.array([2,34,41,32,23,122,2,3,5,678,45,675,34,34])
print(arr)
print()
print(arr[1:])
print()
print(arr[1::3])
print()
print(arr[:3])


[  2  34  41  32  23 122   2   3   5 678  45 675  34  34]

[ 34  41  32  23 122   2   3   5 678  45 675  34  34]

[34 23  3 45 34]

[ 2 34 41]


**Python list slicing**

In [ ]:
arr = [1,2,5,6,7,3,5,6]
print(arr[:-2])


[1, 2, 5, 6, 7, 3]


**Numpy slicing on 2D array**

In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[:-1,:-1])
print()
print(arr)


[[0 1]
 [3 4]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Linspace and empty_like**

In [ ]:
import numpy as np
a = np.linspace(1,5,num=3)
print(a)
print()
b = np.empty_like(a)
print(b)


[1. 3. 5.]

[1. 3. 5.]


**Random array and shape**

In [ ]:
import numpy as np
arr = np.random.rand(2,3)
print(arr)
print()
arr.shape


[[0.20517246 0.92906376 0.87493669]
 [0.48166838 0.41842628 0.28711631]]



(2, 3)

**Empty_like on random array**

In [ ]:
import numpy as np
arr = np.random.rand(2,3)
print(arr)
print()
b = np.empty_like(arr)
print(b)


[[0.17062445 0.04504986 0.4785158 ]
 [0.95798263 0.27574552 0.28662388]]

[[0.17062445 0.04504986 0.4785158 ]
 [0.95798263 0.27574552 0.28662388]]


**Empty_like on 1D array**

In [ ]:
import numpy as np
arr = np.array([1,3,4,5,5,7])
print(arr)
print()
array = np.empty_like(arr)
print(array)


[1 3 4 5 5 7]

[4595315414051503312 4586653189737636240 4602291794245227630
 4606803960019854471 4598639009527650324 4598834976637616836]


**Iterating over 1D array**

In [ ]:
import numpy as np
arr = np.array([1,3,4,5,5,7])
print(arr)
print()
for i in arr:
    print(i)


[1 3 4 5 5 7]

1
3
4
5
5
7


**Nested iteration over 2D array**

In [ ]:
import numpy as np
arr = np.array([1,3,4,5,5,7]).reshape(3,2)
print(arr)
print()
for i in arr:
    for j in i:
        print(j)


[[1 3]
 [4 5]
 [5 7]]

1
3
4
5
5
7


**3D array with full**

In [ ]:
import numpy as np
array = np.full((3,3,3),2)
print(array)
print()
array.shape


[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]



(3, 3, 3)

**Array properties (type, shape, size)**

In [ ]:
import numpy as np
a = np.array([[1,2],[3,2]])
print(arr)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)


[[1 3]
 [4 5]
 [5 7]]
<class 'numpy.ndarray'>
(2, 2)
2
4
int64


**3D array attributes**

In [ ]:
import numpy as np
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[10, 11, 12],
     [13, 14, 15]]
])
print(arr)
print()
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]

(2, 2, 3)
3
12
int64


**Triple nested iteration over 3D array**

In [ ]:
import numpy as np
A = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print(A)
print()
for i in A:
    for j in i:
        for k in j:
            print(k)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


**Different dtypes in arrays**

In [ ]:
import numpy as np
a = np.ndarray(shape=(3,3),dtype=float)
print(a)
print()
b = np.ones((3,3),dtype=int)
print(b)
print()
c = np.zeros((3,3))
print(c)
print()
d = np.full((3,3),1,dtype=complex)
print(d)


[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323 4.0e-323]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


**Indexing element in 2D array**

In [ ]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[1][1])


50


**Negative indexing in 2D array**

In [ ]:
import numpy as np
arr = np.array([[10,20,30],[4,3,2]])
print(arr)
print()
print(arr[1,-1])


[[10 20 30]
 [ 4  3  2]]

2


**Modifying an element in array**

In [ ]:
import numpy as np
A = np.array([[1,2],
              [3,5],
              [15,-3]])
print(A)
print()
A[2,1] = 100
print(A)


[[ 1  2]
 [ 3  5]
 [15 -3]]

[[  1   2]
 [  3   5]
 [ 15 100]]


**Array arithmetic operations**

In [ ]:
import numpy as np
a = np.array([[1,2],[3,5],[15,-3]])
print(a)
b = np.array([[1,2],[3,5],[15,-3]])
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[ 1  2]
 [ 3  5]
 [15 -3]]
[[ 1  2]
 [ 3  5]
 [15 -3]]
[[ 2  4]
 [ 6 10]
 [30 -6]]
[[0 0]
 [0 0]
 [0 0]]
[[  1   4]
 [  9  25]
 [225   9]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


**Finding item size of array elements**

In [ ]:
import numpy as np
a = np.array([[1,2],[3,5],[15,2]])
print(a.itemsize)


8


**Sorting elements in arrays**

In [ ]:
import numpy as np
a = np.array([[1,4],[6,5],[15,2]])
print(a)
print()
b = np.sort(a)
print(b)


[[ 1  4]
 [ 6  5]
 [15  2]]

[[ 1  4]
 [ 5  6]
 [ 2 15]]


**Concatenating 1D arrays**

In [ ]:
import numpy as np
a = np.array([2,-1,0,15,5])
print(a)
b = np.array([10,20,5])
print(b)
c = np.concatenate((a,b))
print(c)


[ 2 -1  0 15  5]
[10 20  5]
[ 2 -1  0 15  5 10 20  5]


**Concatenating 2D arrays along different axes**

In [ ]:
import numpy as np
a = np.array([[2,-1,0,15,5],[1,1,1,1,0]])
print(a)
print()
b = np.array([[10,20,5,1,3],[10,2,-1,4,5]])
print(b)
print()
c = np.concatenate((a,b),axis=1)
print(c)
print()
d = np.concatenate((a,b),axis=0)
print(d)


[[ 2 -1  0 15  5]
 [ 1  1  1  1  0]]

[[10 20  5  1  3]
 [10  2 -1  4  5]]

[[ 2 -1  0 15  5 10 20  5  1  3]
 [ 1  1  1  1  0 10  2 -1  4  5]]

[[ 2 -1  0 15  5]
 [ 1  1  1  1  0]
 [10 20  5  1  3]
 [10  2 -1  4  5]]


**Stacking arrays horizontally and vertically**

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
e = np.stack((a,b),axis=1)
print(e)
print()
c = np.hstack([a,b])
d = np.vstack([a,b])
print(c)
print()
print(d)


[[1 5]
 [2 6]
 [3 7]]

[1 2 3 5 6 7]

[[1 2 3]
 [5 6 7]]


**Splitting arrays**

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
result = np.array_split(a,3)
print(result)
b = np.split(a,1)
print(b)


[array([1, 2]), array([3, 4]), array([5])]
[array([1, 2, 3, 4, 5])]


**Splitting 2D arrays horizontally and vertically**

In [ ]:
import numpy as np
a = np.array([[1,3,42,32,50,60],
              [43,55,42,45,70,80]])
result = np.hsplit(a,3)
print(result)
print()
result = np.vsplit(a,1)
print(result)


[array([[ 1,  3],
       [43, 55]]), array([[42, 32],
       [42, 45]]), array([[50, 60],
       [70, 80]])]

[array([[ 1,  3, 42, 32, 50, 60],
       [43, 55, 42, 45, 70, 80]])]


**Finding indices using where**

In [ ]:
import numpy as np
n = np.array([12,43,54,6,45,45])
print(n)
print()
arr = np.where(n==45)
print(arr)


[12 43 54  6 45 45]

(array([4, 5]),)


**Sorting 1D arrays**

In [ ]:
import numpy as np
arr = np.array([5,2,9,1,7])
sorted_arr = np.sort(arr)
print("Original:")
print(arr)
print("Sorted:")
print(sorted_arr)


Original:
[5 2 9 1 7]
Sorted:
[1 2 5 7 9]


**Sorting ascending and descending**

In [ ]:
import numpy as np
arr = np.array([5,2,9,1,7])
sorted_arr = np.sort(arr)
reversed_arr = sorted_arr[::-1]
print("Original:",arr)
print("Sorted (ascending):",sorted_arr)
print("Sorted (descending):",reversed_arr)


Original: [5 2 9 1 7]
Sorted (ascending): [1 2 5 7 9]
Sorted (descending): [9 7 5 2 1]


**Intersection of arrays**

In [ ]:
import numpy as np
n = np.array([1,73,54,6,95,45])
print(n)
print()
b = np.array([1,73,754,86,95,845])
print(b)
print()
result = np.intersect1d(n,b)
print(result)


[ 1 73 54  6 95 45]

[  1  73 754  86  95 845]

[ 1 73 95]


**Finding rank of matrix**

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
rank = np.linalg.matrix_rank(A)
print(A)
print()
print(rank)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

2


**Trace of matrix**

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
trace = np.trace(A)
print(trace)


15


**Determinant of matrix**

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
det = np.linalg.det(A)
print(det)


0.0


**Inverse of matrix**

In [ ]:
import numpy as np
A = np.array([[4,7],
              [2,6]])
inverse = np.linalg.inv(A)
print(inverse)


[[ 0.6 -0.7]
 [-0.2  0.4]]


**Eigenvalues and eigenvectors**

In [ ]:
import numpy as np
A = np.array([[4,-2],
              [1,1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:",eigenvalues)
print("Eigenvectors:\n",eigenvectors)


Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


**Normal distribution random numbers**

In [ ]:
import numpy as np
data = np.random.normal(0,1,10)
print(data)


[ 0.14869985  1.03922637 -0.8409645  -1.20034812 -1.10556371 -0.37176455
 -0.55602263 -0.34745688 -0.5659265  -0.51025203]


**Uniform distribution random numbers**

In [ ]:
import numpy as np
data = np.random.uniform(0,1,10)
print(data)


[0.112218   0.56924113 0.85250005 0.8557451  0.11473403 0.35254904
 0.00784392 0.06658794 0.99668846 0.44293584]


**Poisson distribution random numbers**

In [ ]:
import numpy as np
data = np.random.poisson(3,10)
print(data)


[2 3 1 2 4 4 8 3 6 3]
